# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '819fbc6a-a3e4-4794-aaa3-470f43bf3d40'

  # Web app name
  webAppName: 'derivcoapp'

  # Environment name
  environmentName: 'derivcoapp'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
  - script: 
      npm install
    displayName: 'npm install'
    workingDirectory: ui